### PR TITLE
Adding Ray's slides for chapter 2

### PR DESCRIPTION
**Pull request by wdefreitas**

### CODE REVIEW

**Review by jonthegeek — COMMENTED** [review]
I'm not going to *require* this to merge, but consider making the sections less wordy. Think of them more as slides and less as a book (despite the bookdown format, I know that can muddy the waters). It's your presentation so I don't want to mandate a format, but aiming for bullets over full sentences can make the key points easier to find in a meeting format.

Let me know what you think, and I'll merge if you want to leave it as is.

In general, this is great, and quite a bit more than I was expecting!

**Comment by RaymondBalise** [comment]
I know it is WAY too many words but I think they will help tie content to specific sections. Hopefully the highlighting will help draw people's attention to the critical content.  I am going to use the book for a class in a few months.  So I am building out the *entire* book in fully annotated markdown.  I can share it with others if they want to pull out formulas and stuff.

**Comment by jonthegeek** [comment]
When you use a new-to-this-project package (such as {ggthemes}), type `usethis::use_package("ggthemes")` (etc) to add it to the description. That way it will auto-install for anybody trying to follow along. I did that for this PR, but just FYI.

> I know it is WAY too many words but I think they will help tie content to specific sections. Hopefully the highlighting will help draw people's attention to the critical content. I am going to use the book for a class in a few months. So I am building out the _entire_ book in fully annotated markdown. I can share it with others if they want to pull out formulas and stuff.

Ok, we'll see how the meeting goes, and make decisions from that!

**Review by jonthegeek — APPROVED** [review]
Looks great!

**Comment by RaymondBalise** [comment]
Cool. Thanks for the good idea on the `usethis`.  I will add that to my workflow in the future.

**Pull request merged**
