### PR TITLE
fix latex eqn rendering

### PR DESCRIPTION
**Pull request by blongworth**
Missing char prevented eqn in section 4.3.1 from rendering

### CODE REVIEW

**Review by jonthegeek — APPROVED** [review]
Thanks!

**Comment by jonthegeek** [comment]
It looks like one of the packages we use was temporarily unavailable on CRAN (when this check ran). Rerunning!

**Review by jonthegeek — APPROVED** [review]
Ok, that seems to have fixed it (finally)!

**Comment by blongworth** [comment]
Sorry it was a bit of a wild goose chase!

**Pull request merged**
