### PR TITLE
Sm bookclub islr

### PR DESCRIPTION
**Pull request by megaxander**
Updates/changes to 05_Resampling-methods.Rmd. Added a figure (fig5_1) and made content and formatting changes.

### CODE REVIEW

**Review by jonthegeek — APPROVED** [review]
Thanks!

I had to add some tick marks back in, and the jpgs that are saved as JPG need to be properly identified. Hopefully the build will work now, and I can merge this in!

**Review by jonthegeek — APPROVED** [review]
For some reason it's freaking out about these images.

**Review by jonthegeek — APPROVED** [review]
I finally resaved all those chapter 5 images as pngs instead of trying to figure out why the jpgs were broken. Builds now.

Thanks for your fixes, sorry that you got lots of spam while I tried to figure out why it wasn't working 🙃

**Comment by megaxander** [comment]
Thank you so much Jon! Yeah most figures did not display properly, but did
work on my local version.
Why does saving them as pngs fix the issue?

**Comment by jonthegeek** [comment]
@megaxander I'm not sure. I just changed them so they'd definitely be different than the failing originals

In general, png was developed to replace both jpg and gif (minus animation), so saving as png usually won't hurt, at least.

**Pull request merged**
