### PR TITLE
Chp 2 image - interpretability vs flexibility 

### PR DESCRIPTION
**Pull request by kevin-m-kent**

### CODE REVIEW

**Review by jonthegeek — DISMISSED** [review]
Looks good!

**Review by jonthegeek — COMMENTED** [review]
Oops, not quite! The block titles have to be unique, and you left the "Editions" caption on that image. I'm fixing it now, but be sure to build the book (whenever possible) before checking things in to make sure everything worked!

**Comment by kevin-m-kent** [comment]
whoops, sorry, thanks for fixing. I rendered the chapter page to html but I guess building the whole book does something different?

**Comment by kevin-m-kent** [comment]
oh I know why - the chunk that had the same name came from another chapter. makes sense

**Comment by jonthegeek** [comment]
> oh I know why - the chunk that had the same name came from another chapter. makes sense

Oh, thanks, yeah usually rendering just the one chapter is enough... but the block names unfortunately have to be unique throughout the whole book (right now, at least; there's a way to do it where each chapter is its own unique thing, and I'll get that sorted out... eventually...)

**Review by jonthegeek — APPROVED** [review]
Ok, *now* I'm approving it, since the build worked!

**Pull request merged**
