### PR TITLE
upload chap4

### PR DESCRIPTION
**Pull request by sohmeiling**
notes for chapter 4: classification

### CODE REVIEW

**Review by jonathanbratt — CHANGES_REQUESTED** [review]
un-approving so that edits will get picked up

**Review by jonthegeek — CHANGES_REQUESTED** [review]
Use `$$` for equations that are on their own line, but `$` for inline equations. You used `$$` throughout, so there are a number of equations that go to a newline and look weird.

Also, when you use a new package, type this in your console to add it to the bookdown: `usethis::use_package("htmlTable")` (or whatever the package is).

Always be sure to render it locally to make sure it looks how you expect!

**Review by sohmeiling — COMMENTED** [review]
Noted with thanks!

**Review by sohmeiling — COMMENTED** [review]
Done with changes.

**Review by jonthegeek — CHANGES_REQUESTED** [review]
Don't put the use_package calls in the RMD. Run them locally, on your computer. That will update the DESCRIPTION file so that others can run the code (the DESCRIPTION identifies packages that are needed to render the book). You still need `library` calls for the packages, `use_package` is just something to run on your machine (NOT in the RMD) to help others.

PLEASE always render the book locally with ctrl-shift-b (command-shift-b on Mac) and fix any errors before pushing to github. That's a good general rule, so you know that it works like you think it works!

I ran these changes locally, but I'm sending it back to you to make sure you understand the difference (and can apply them). Let me know if you need help with anything!

**Review by sohmeiling — COMMENTED** [review]
I have updated the rmd file and separately ran the `usethis_use_package`. Let me know if there is anything else that I have missed.

**Review by jonthegeek — APPROVED** [review]
Looks good!

**Pull request merged**
